s1 = input("Enter string s1:")
s2 = input("Enter string s2:")
print("The strings s1 and s2 are:", s1, s2)
print("Number of occurrences of s2 in s1:", s1.count(s2))
print("The left position of s2 in s1 is:", s1.find(s2))
print("The right position of s2 in s1 is:", s1.rfind(s2))