str = input("Enter a string:")
print("The String is:", str)
print("Capitalize:", str.capitalize())
print("Title:", str.title())
print("Lower:", str.lower())
print("Upper:", str.upper())
print("Swapcase:", str.swapcase())
print("Count number of a:", str.count("a"))
print("Casefold:", str.casefold())
print("Printable:", str.isprintable())
print("Startswith a:", str.startswith("a"))
print("Endswith z:", str.endswith("z"))